### ISSUE TITLE
Codegenerator-Plugin-Intellij 这个也不错

### ISSUE THREAD

**Issue by nuptboyzhb** [maoruibin/AwesomeAndroidStudioPlugin#1]
[Codegenerator-Plugin-Intellij](https://github.com/tmorcinek/android-codegenerator-plugin-intellij) | [下载](https://github.com/tmorcinek/android-codegenerator-plugin-intellij) | 由xml layout自动生成Fragment、ViewHolder、Activity等，免去写findViewById的问题

**Comment by maoruibin** [comment]
恩，确实不错，我加进来了！Thanks ~

**Comment by maoruibin** [comment]
其实你可以自己直接fork 、编辑然后提交到项目 ！这次我手动加上去了，如果还有，你可以直接加上去的！
